### ISSUE TITLE
Bourbon/bitters/neat option

### ISSUE THREAD

**Issue by patbenatar** [philosophie/suspenders#14]
https://github.com/philosophie/suspenders/commit/7cd873c8e3fd35135d5ae55c6f5c2e0a3ffbf511
https://github.com/philosophie/suspenders/commit/9fe8e01fd796ab92d5309bf306c76f6b595ec494

**Comment by lexi-lambda** [comment]
@taboularasa Is this done?

**Comment by taboularasa** [comment]
@lexi-lambda yes
