### ISSUE TITLE
API option

### ISSUE THREAD

**Issue by patbenatar** [philosophie/suspenders#15]

**Comment by taboularasa** [comment]
@jdwolk @patbenatar I plan on porting over our work from curbstand 3 into this. primarily our documentation / testing setup. on the issue of adopting `rails-api` I vote that if we do we should wait until rails 5 when it will be baked in. but how do you guys feel about that being defaulted into this template at all? I know @patbenatar has some bones to pick with `rails-api`...

**Comment by patbenatar** [comment]
@taboularasa Agreed we wait til Rails 5 on that.. regarding me picking bones: the reason I generally avoid `rails-api` is the same reason I generally avoid sinatra.. requirements change/grow and all of a sudden we want something that is ripped out of `rails-api`. For instance, if we needed to quickly spin up an admin dashboard, it'd be a pain to do on `rails-api`.

**Comment by patbenatar** [comment]
I think tools like that are great when requirements are more specific... e.g. optimizing a specific component out of a monolith app into a dedicated service — that's when sinatra/express/etc become goto tools

**Comment by patbenatar** [comment]
@taboularasa should we close this out for now and revisit when Rails 5 comes out?

**Comment by taboularasa** [comment]
Yes let's close 

—
