### ISSUE TITLE
What needs to be removed or changed?

### ISSUE THREAD

**Issue by patbenatar** [philosophie/suspenders#2]
@jdwolk @taboularasa @cltatman @pgdaniel can you guys let me know what you had to remove or change after using suspenders to generate a project?

**Comment by taboularasa** [comment]
@patbenatar I vote we work on this incrementally. Theres a lot of stuff in there, some of which we don't use because we're unfamiliar, less of it we don't use because we specifically don't like. We can start using this fork and discuss over pull requests during each new project that uses it?

**Comment by patbenatar** [comment]
@taboularasa I'm on board with that.. My goal with this issue is a first step to understand what everyone has been removing. The overlap between those lists will help us to consider whether we should introduce new tooling into our stack or prune out the obvious removals.

**Comment by taboularasa** [comment]
some things we probably can remove initially:
- `.travis.yml`
- bourbon
- neat
- refills
- email_validator
- high_voltage
- web-console
- awesome_print
- byebug (I think pry-rails already depends on this)

Things maybe we should remove?
- title gem (probably won't get used very often)
- formulaic (tried this already and doesn't work very well)
- simplecov (lies, also we already have this with code climate)
- webmock (does not need to be on every project)
- rack-timeout (this is just a pain in the ass, if requests are running this long and you're not in a binding then you should know about it anyway)

Things we should evaluate?
- dotenv-rails
- flutie
- autoprefixer-rails
- i18n-tasks
- normalize-rails
- rack-canonical-host
- recipient_interceptor

Things we should probably add:
- better_errors
- binding_of_caller

**Comment by jdwolk** [comment]
- byebug -> pry-byebug

**Comment by taboularasa** [comment]
@jdwolk does pry-rails not take care of byebug dependency?

**Comment by jdwolk** [comment]
@taboularasa don't believe so -- every time I leave in just `pry-rails` it chokes on `continue` until I add `pry-byebug`. 

Also `byebug` by itself doesn't integrate w/ pry. Hence `byebug` -> `pry-byebug`

**Comment by jdwolk** [comment]
![screen shot 2015-06-08 at 10 19 20 am 2](https://cloud.githubusercontent.com/assets/117333/8040778/0b3d3fca-0dc8-11e5-91ec-55eb26dfe35f.png)

**Comment by taboularasa** [comment]
@jdwolk okthen. I was thinking that the newer version of pry-rails was not trying to be backwards compatible

**Comment by patbenatar** [comment]
@cltatman @jdwolk can you guys provide your lists of what you removed for CGC and CSL as well? Thanks!

**Comment by patbenatar** [comment]
@taboularasa is the main problem with `rack-timeout` that it gets in the way of bindings during development?

**Comment by patbenatar** [comment]
WIP documentation of what to keep/remove/eval https://docs.google.com/spreadsheets/d/1NsBnXRFi_eQCgSUOXFhCcBA-NRYxj66P5qJ_0RoNKLU/edit#gid=0

**Comment by etaymor** [comment]
@patbenatar jumping in here, if you are setting up an option for bootstrap / foundation, could you set one up for Bourbon & friends too. NYC team tends to enjoy working with Bourbon / Neat / Bitters over Bootstrap and I find it a lot better to use

**Comment by patbenatar** [comment]
@etaymor Ha, we just ripped all that stuff out. But agreed they all have their use cases, depends on how heavily you want/need to customize

**Comment by taboularasa** [comment]
@etaymor @patbenatar if we're going with the command line flags it makes sense to have Bourbon to be one of the options. I can add that back in if you want

**Comment by patbenatar** [comment]
All initial removals and additions have been either completed or documented in individual issues. Items to be evaluated have individual tasks on the trello board
