### ISSUE TITLE
Need to run airbrake generator to create initializer

### ISSUE THREAD

**Issue by patbenatar** [philosophie/suspenders#26]
Consider using `--heroku` option to have the initializer look for `AIRBRAKE_API_KEY` in the environment.

**Comment by patbenatar** [comment]
https://github.com/airbrake/airbrake/blob/83ffb0080ed8b94774effd6146a1919b77b5a289/README_FOR_HEROKU_ADDON.md

**Comment by taboularasa** [comment]
do we have an airbrake account now?

**Comment by patbenatar** [comment]
@taboularasa No, but we can either a) add the free tier to heroku apps; or b) have the client sign up for paid tier

**Comment by patbenatar** [comment]
``` ruby
if ENV.include?('AIRBRAKE_API_KEY')
  Airbrake.configure do |config|
    config.api_key = ENV.fetch('AIRBRAKE_API_KEY')
  end
end
```

**Comment by patbenatar** [comment]
Remove `say "Remember to run 'rails generate airbrake' with your API key."` from outro as it will be read from ENV. Ping #10 needs to add that env var if you want it in dev
