### ISSUE TITLE
Make `--heroku` default, add `--skip-heroku` option

### ISSUE THREAD

**Issue by patbenatar** [philosophie/suspenders#32]
I'm adding some setup for Heroku (airbrake, papertrail, sendgrid, etc) that should be baseline on all new servers. Defaulting to creating heroku apps automatically and providing a `--skip-heroku` option to skip it would prevent users from mistakenly skipping this step and forgetting this kind of configuration when manually setting up their heroku servers.

**Comment by taboularasa** [comment]
I think we can start with it default and wait for people to complain about it
