### ISSUE TITLE
How should we release this?

### ISSUE THREAD

**Issue by patbenatar** [philosophie/suspenders#41]
Some options I can think of:
1. Build it and distribute the `.gem` file manually
2. Install from GitHub source with something like https://github.com/rdp/specific_install
3. Distribute via Rubygems under a name like `suspenders-philosophie`

**Comment by taboularasa** [comment]
I vote for `suspenders-philosophie` the repo is already public and changing the name will make it obvious that we have the correct one installed

**Comment by taboularasa** [comment]
or maybe it would be `philosophies-suspenders`

**Comment by patbenatar** [comment]
:+1: for `philosophies-suspenders`. Agreed, rubygems easiest way to distro this.
