### ISSUE TITLE
Replace web-console with better_errors

### ISSUE THREAD

**Issue by lexi-lambda** [philosophie/suspenders#42]

**Comment by patbenatar** [comment]
:+1: We should also add `binding_of_caller` so we get the advanced debug features.

Note that `web-console` additionally adds a generic rails console that can be accessed via the browser.. I don't ever use this (prefer the terminal one), but for the sake of comparison it's not quite apples-to-apples with `better_errors`. I still vote we remove `web-console` in favor of this.
