### ISSUE TITLE
Remove high_voltage

### ISSUE THREAD

**Issue by lexi-lambda** [philosophie/suspenders#43]
Suggested by @taboularasa. Do we need this by default?

**Comment by patbenatar** [comment]
Every non-API site will have at least 2 static pages (Terms of Service and Privacy Policy). Perhaps we toggle this in conjunction with #15, so it is removed if we are generating a purely API app.

**Comment by taboularasa** [comment]
I vote we ditch high_voltage in favor of having a pages controller to seven static content

**Comment by taboularasa** [comment]
"Serve static content"

**Comment by taboularasa** [comment]
Haha phone gone wild

**Comment by patbenatar** [comment]
@taboularasa How come?

The way I see it, we have two main goals with this project:
1. Save time
2. Converge

If `high_voltage` saves us even just 2-5 minutes on each project, I would say that justifies keeping it in. Also, adopting this out-of-the-box convention would make it a tad bit easier to train designers so they can add static pages without any intervention from dev.

**Comment by patbenatar** [comment]
:fireworks: :us: happy 4th!

**Comment by taboularasa** [comment]
I would have agreed in the past but had a high voltage fail experience with Brooke that cost a combined hour so we both vowed to not do that again. Pages control only takes a sec and does essentially the same thing

**Comment by taboularasa** [comment]
And happy fourth!

**Comment by patbenatar** [comment]
That's no good. What happened?

**Comment by taboularasa** [comment]
I forget, it was her problem I was just helping. Something about magic not working as expected.

—

**Comment by taboularasa** [comment]
Anyway what's wrong with just add a new method when you need another marketing page, easy least no magic required

**Comment by patbenatar** [comment]
@taboularasa OK... not worth it if the magic has already proven to break. Agreed it's trivial to add manually, but I do generally want to avoid going down that route of reasoning for this project as you could say the same about many of the small changes we're making (in isolation they're pretty trivial to do).

:-1:

**Comment by patbenatar** [comment]
@lexi-lambda can you take care of this ticket?
