### ISSUE TITLE
Use rails-assets for jQuery instead of jquery-rails

### ISSUE THREAD

**Issue by lexi-lambda** [philosophie/suspenders#45]
I recently ran into a problem with using gems like `jquery-rails` in conjunction with packages from rails-assets. Since rails-assets is just Bower, it translates Bower dependencies into gem dependencies, which is good. However, if a rails-assets gem depends on jquery, `jquery-rails` will be ignored, and `rails-assets-jquery` will be installed instead. The means two different versions of jQuery can be installed side-by-side.

This wasn't a problem with jQuery itself, but it was a problem with Angular, so I'd advocate for providing all front-end assets via rails-assets for proper dependency management. I've also added a note to the Dev Roundup doc to discuss this next Friday.

**Comment by patbenatar** [comment]
Yes! :+1: :star2: 

We should use `rails-assets` for all front-end deps.

**Comment by patbenatar** [comment]
@philosophie/devs please chime in on this one

**Comment by taboularasa** [comment]
:+1:

—

**Comment by cltatman** [comment]
sounds good to me, don't know of any pain points around working with rails-assets

**Comment by pgdaniel** [comment]
:+1:
