### ISSUE TITLE
Carrierwave?

### ISSUE THREAD

**Issue by patbenatar** [philosophie/suspenders#53]
Should we:
- Include carrierwave in Gemfile
- Setup FS storage in dev, and AWS storage on Heroku

?

**Comment by taboularasa** [comment]
I vote no.

**Comment by patbenatar** [comment]
@taboularasa Why not? It helps if you can provide some detail when downvoting.

**Comment by taboularasa** [comment]
Haha oh ya. I vote no because not every project needs file upload. That's all

**Comment by taboularasa** [comment]
Add a optional argument? Maybe but overall I'm a little worried about keeping all this configuration up to date so I'm inclined to resist adding more than core requirements

**Comment by patbenatar** [comment]
@taboularasa Yeah, I agree with that concern.. It's not trivial to do this one either, since it would require setting up AWS buckets for staging and production apps. Canning it for now.
