### ISSUE TITLE
Compass option

### ISSUE THREAD

**Issue by pigstake** [philosophie/suspenders#58]
http://compass-style.org/

alternative to Bourbon
compiles with Ruby, rather than Sass
has a useful Sprite generator
plays nice with Susy AFAIK

**Comment by patbenatar** [comment]
@pigstake we need to be careful to avoid fragmentation.. we already have 1) the Bourbon/Neat/Bitters stack; 2) Foundation (I believe this comes with Compass as well); and 3) Bootstrap. Looks like this and #57 are proposing yet another frontend stack.

Has anyone used a Susy/Compass setup as the framework on a project yet?

**Comment by pigstake** [comment]
@patbenatar My assumption is that they are modular add-ons. Where does fragmentation come in? Is it cumbersome or inelegant to include Compass with Foundation and then also with a Compass/Susy stack? 

AFAIK, no project frontend currently runs on Susy/Compass. I'd like to use it on Delmondo or another upcoming project, though.

**Comment by patbenatar** [comment]
@pigstake My concern is fragmentation of our tooling/tech... If we are releasing projects using N number of frameworks, we now have to train the team on N frameworks so we have flexibility with regards to who is supporting any given project, or if the project returns for an additional phase of development and we re-staff it... if the team isn't trained/familiar with the tool, the ramp up time becomes more costly.

That's not to say we shouldn't be experimenting with new things, however: Suspenders is intended to represent a default/goto stack that the team converges on, so I'd like to see any new tools/approaches/frameworks/etc tried out on 1 or 2 individual projects before being considered for adoption across the entire team.

What do you think?

**Comment by pigstake** [comment]
@patbenatar That makes sense. In that case, adding the Bourbon stack was probably a gun jump, since only one project is currently using it. It was overall a happy experiment, but we should really give Compass/Susy a whirl before making a decision on what to include as a standard Philo tool.

_edit_ I'm assuming that we decide to use either Bourbon/Neat or Compass/Susy as a standard tool.

Any designers or engineers over in LA have thoughts on using one or the other?

**Comment by patbenatar** [comment]
@pigstake Ah.. well we have Bourbon/Neat ready to merge in #20 so we'll keep that for now but can make the change to Compass/Susy after both have been evaluated and a decision made. OK if I close this for now and we revisit later?

**Comment by pigstake** [comment]
:+1:
