### ISSUE TITLE
Remove rack-timeout

### ISSUE THREAD

**Issue by patbenatar** [philosophie/suspenders#70]
https://trello.com/c/ccRvABjw/41-eval-gem-rack-timeout

**Comment by jdwolk** [comment]
yes lets -- just scratched my head over `PG::DuplicatePstatement: ERROR: prepared statement "a2" already exists` errors, which turn out to be a potential side-effect of running `Rack::Timeout`: https://stackoverflow.com/questions/26146436/how-to-fix-pgduplicatepstatement-error , https://github.com/rails/rails/pull/17607

**Comment by patbenatar** [comment]
@jdwolk @wykhuh :+1: — can one of you PR the removal of this?

**Comment by jdwolk** [comment]
@patbenatar sho thang
