### ISSUE TITLE
The SMTP configuration should include support for SendGrid

### ISSUE THREAD

**Issue by lexi-lambda** [philosophie/suspenders#76]
Mandrill (currently) no longer has a free tier on Heroku. Since we already branch in `config/smtp.rb` for Mandrill, it would be easy to add support for SendGrid, too.

**Comment by taboularasa** [comment]
@lexi-lambda you should add that

**Comment by lexi-lambda** [comment]
Yep, I've already done it locally, so it'll be easier to add to the generator.

**Comment by taboularasa** [comment]
:dancers:
