### ISSUE TITLE
How does spec_helper get included in rails_helper?

### ISSUE THREAD

**Issue by lexi-lambda** [philosophie/suspenders#84]
As far as I can tell, right now the answer seems to be "it doesn't". Even so, sometimes it seems to be loaded, but I can't figure out why or how.

Shouldn't there be an explicit `require 'spec_helper'`?

**Comment by lexi-lambda** [comment]
Actually, it looks like it gets included via the `.rspec` file, which includes `--require spec_helper`. If we do it that way, we need to remove `.rspec` from `.gitignore`. Otherwise, we _need_ to explicitly require `spec_helper` in `rails_helper`.

**Comment by taboularasa** [comment]
I vote we remove `.rspec`
