### ISSUE TITLE
Suspenders should generate projects that use ES6 via Babel instead of CoffeeScript

### ISSUE THREAD

**Issue by lexi-lambda** [philosophie/suspenders#92]
This means:
- Babel transpiler for asset pipeline
- Use eslint with reasonable defaults

**Comment by ebramanti** [comment]
@lexi-lambda We have an `.eslintrc` file currently on handbook. I'll look to improve it next week.

**Comment by patbenatar** [comment]
Let's hold off until Rails 5 ships with support for it.. if we can
